updated CI

diff --git a/.gitlab-ci.yml b/.gitlab-ci.yml
--- a/.gitlab-ci.yml
+++ b/.gitlab-ci.yml
@@ -27,7 +27,7 @@ stages:
 
 # global before_script is run before each and every job.
 before_script:
-- 'source ${VENVNAME}/bin/activate'
+- source ${VENVNAME}/bin/activate
 
 ################
 # STAGE: SETUP #
@@ -44,18 +44,18 @@ setup:
     - "${VENV_DIR}"
   before_script:
   # make directories
-  - 'mkdir badges'
-  - 'mkdir reports'
+  - mkdir badges
+  - mkdir reports
   # python setup
-  - 'python -V'
-  - 'pip install --upgrade pip virtualenv'
-  - 'virtualenv ${VENVNAME}'
-  - 'source ${VENVNAME}/bin/activate'
-  - 'pip install --upgrade pip pybadges'
+  - python -V
+  - pip install --upgrade pip virtualenv
+  - virtualenv ${VENVNAME}
+  - source ${VENVNAME}/bin/activate
+  - pip install --upgrade pip pybadges
   script:
   # install dependencies
-  - 'pip install --upgrade -r requirements.txt'
-  - 'pip install --upgrade -r requirements-extra.txt'
+  - pip install --upgrade -r requirements.txt
+  - pip install --upgrade -r requirements-extra.txt
   - |
     if [[ $CI_PROJECT_URL == *"git.tu-berlin.de"* ]]; then
       pip install tsdm --upgrade --no-deps --index-url https://gitlab-ci-token:${CI_JOB_TOKEN}@git.tu-berlin.de/api/v4/projects/6694/packages/pypi/simple
@@ -65,14 +65,13 @@ setup:
       exit 1
     fi
   # build and install package
-  - 'python setup.py sdist bdist_wheel'
-  - 'pip install dist/*.whl'
-  - 'pip list'
+  - python setup.py sdist bdist_wheel
+  - pip install dist/*.whl
+  - pip list
   after_script:
-  - 'source ${VENVNAME}/bin/activate'
+  - source ${VENVNAME}/bin/activate
   # generate python version badge
-  - >
-    python -m pybadges
+  - python -m pybadges
     --left-text="python"
     --right-text="3.9"
     --whole-link="https://www.python.org/"
@@ -80,14 +79,12 @@ setup:
     --embed-logo
     > badges/python.svg
   # generate package version badge
-  - >
-    python -m pybadges
+  - python -m pybadges
     --left-text="version"
     --right-text="$(cat "$MODULEDIR/VERSION")"
     > badges/version.svg
   # generate license badge
-  - >
-    python -m pybadges
+  - python -m pybadges
     --left-text="license"
     --right-text="MIT"
     --right-color="#7900CA"
@@ -114,23 +111,21 @@ pylint:
   - setup
   script:
   # generate reports
-  - |
-    pylint $MODULEDIR
+  - pylint $MODULEDIR
     --exit-zero
     --load-plugins=pylint_gitlab
     --output-format=gitlab-codeclimate
     > reports/codeclimate.json
   # colorized for human readability
-  - 'pylint $TESTDIR --exit-zero --output-format=colorized'
-  - 'pylint $MODULEDIR --exit-zero --output-format=colorized | tee pylint.log'
+  - pylint $TESTDIR --exit-zero --output-format=colorized
+  - pylint $MODULEDIR --exit-zero --output-format=colorized | tee pylint.log
   after_script:
-  - 'source ${VENVNAME}/bin/activate'
-  - 'SCORE=$(sed -n "s/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p" pylint.log)'
+  - source ${VENVNAME}/bin/activate
+  - SCORE=$(sed -n "s/^Your code has been rated at \([-0-9.]*\)\/.*/\1/p" pylint.log)
   - |
     COLOR=$(python -c "print({0: 'black', 2:'red', 4:'orange', 6:'yellow', 8:'green'}[int($SCORE-$SCORE%2)])")
   # generate pylint badge
-  - >
-    python -m pybadges
+  - python -m pybadges
     --left-text="PyLint"
     --right-text="$SCORE"
     --right-color=$COLOR
@@ -155,24 +150,22 @@ flake8:
   needs:
   - setup
   script:
-  - 'flake8 $MODULEDIR'
-  - 'flake8 $TESTDIR'
-  - 'isort $MODULEDIR --check-only --diff'
+  - flake8 $MODULEDIR
+  - flake8 $TESTDIR
+  - isort $MODULEDIR --check-only --diff
   after_script:
-  - 'source ${VENVNAME}/bin/activate'
-  - 'COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")'
-  - 'TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")'
+  - source ${VENVNAME}/bin/activate
+  - COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")
+  - TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")
   # generate flake8 badge
-  - >
-    python -m pybadges
+  - python -m pybadges
     --left-text="flake8"
     --right-text="$TEXT"
     --right-color="$COLOR"
     --whole-link="https://flake8.pycqa.org/en/latest/"
     > badges/flake8.svg
   # generate black code style badge
-  - >
-    python -m pybadges
+  - python -m pybadges
     --left-text="code style"
     --right-text="black"
     --right-color="black"
@@ -195,15 +188,14 @@ mypy:
   needs:
   - setup
   script:
-  - 'mypy $MODULEDIR --show-error-codes --pretty --junit-xml reports/mypy.xml'
-  - 'mypy $TESTDIR --show-error-codes --pretty --junit-xml reports/mypy_test.xml'
+  - mypy $MODULEDIR --show-error-codes --pretty --junit-xml reports/mypy.xml
+  - mypy $TESTDIR --show-error-codes --pretty --junit-xml reports/mypy_test.xml
   after_script:
-  - 'source ${VENVNAME}/bin/activate'
-  - 'COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")'
-  - 'TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")'
+  - source ${VENVNAME}/bin/activate
+  - COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")
+  - TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")
   # generate mypy badge
-  - >
-    python -m pybadges
+  - python -m pybadges
     --left-text="MyPy"
     --right-text="$TEXT"
     --right-color="$COLOR"
@@ -235,16 +227,15 @@ pytest:
   needs:
   - setup
   script:
-  - 'pytest --junitxml=reports/pytest.xml --cov=$MODULEDIR $TESTDIR --reruns 3 --only-rerun AssertionError'
-  - 'coverage xml -o reports/coverage.xml'
-  - 'coverage report'
+  - pytest --junitxml=reports/pytest.xml --cov=$MODULEDIR $TESTDIR --reruns 3 --only-rerun AssertionError
+  - coverage xml -o reports/coverage.xml
+  - coverage report
   after_script:
-  - 'source ${VENVNAME}/bin/activate'
-  - 'COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")'
-  - 'TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")'
+  - source ${VENVNAME}/bin/activate
+  - COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")
+  - TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")
   # generate pytest badge
-  - >
-    python -m pybadges
+  - python -m pybadges
     --left-text="pytest"
     --right-text="$TEXT"
     --right-color="$COLOR"
@@ -278,14 +269,13 @@ pypi:
   only:
   - master
   script:
-  - 'twine upload --verbose  dist/*'
+  - twine upload --verbose  dist/*
   after_script:
-  - 'source ${VENVNAME}/bin/activate'
-  - 'COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")'
-  - 'TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")'
+  - source ${VENVNAME}/bin/activate
+  - COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")
+  - TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")
   # generate pypi badge
-  - >
-    python -m pybadges
+  - python -m pybadges
     --left-text="PyPI"
     --right-text="$TEXT"
     --right-color="$COLOR"
@@ -311,16 +301,15 @@ pages:
   only:
   - master
   script:
-  - 'cd docs'
-  - 'make html'
-  - 'mv  _build ../public/'
+  - cd docs
+  - make html
+  - mv  _build ../public/
   after_script:
-  - 'source ${VENVNAME}/bin/activate'
-  - 'COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")'
-  - 'TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")'
+  - source ${VENVNAME}/bin/activate
+  - COLOR=$([ "$CI_JOB_STATUS" == "success" ] && echo "green" || echo "red")
+  - TEXT=$([ "$CI_JOB_STATUS" == "success" ] && echo "passing" || echo "failed")
   # generate sphinx badge
-  - >
-    python -m pybadges
+  - python -m pybadges
     --left-text="docs"
     --right-text="$TEXT"
     --right-color="$COLOR"
