updated pre-commit

diff --git a/.pre-commit-config.yaml b/.pre-commit-config.yaml
--- a/.pre-commit-config.yaml
+++ b/.pre-commit-config.yaml
@@ -54,7 +54,7 @@ repos:
         exclude: '^experiments/'
   # personal hooks
   - repo: https://github.com/randolf-scholz/assorted-hooks.git
-    rev: v0.6.14
+    rev: v0.6.15
     hooks:
       # pygrep hooks
       - id: check-separator-length-88
@@ -85,13 +85,13 @@ repos:
           - "--allow-two"
           - "--"
       # script-based hooks
+      - id: check-clean-interface
+        files: '^src/'
+        exclude: '/tests/'
       - id: update-requirements
       - id: check-requirements-valid
       - id: check-requirements-maintained
       - id: check-requirements-used
-      - id: check-clean-interface
-        files: '^src/'
-        exclude: '/tests/'
       # other hooks
       - id: check-archived-hooks
       - id: check-resolved-github-issues
@@ -127,37 +127,6 @@ repos:
         entry: '\#\s+\#\s+'
         types: [python]
         files: '^src/|^tests/'
-  # pyright
-  - repo: https://github.com/RobertCraigie/pyright-python
-    rev: v1.1.397
-    hooks:
-      - id: pyright
-        # SEE: https://stackoverflow.com/a/20401674
-        #        entry: sh -c '! script -c "pyright $*" /dev/null | grep --color=never -Po "(?<=$PWD/)(.*:.*)"' --
-        # simple grep: grep --color=never -Po "$PWD/.*:.*"
-        # better ripgrep: rg --multiline --multiline-dotall "($PWD/[^\n]*?)(?:\n.*?)?(\(report\w+\))" -or '$1 $2'
-        # perl:  perl -0777 -ne "while (/((?:\x20+)(${path}[^\n\r]*?)(?:[\r\n].*?)?(\(report\w+\)))/gms) { print \"\$1 \$2\n\"}"
-        # FIXME: some weird issues with ripgrep + script.
-        # NOTE: The issue is likely control characters that are not being handled correctly.
-        #   In fact, it turns out the problem is precisely carriage return. We need to check [\n\r] instead of just \n
-#        entry: |
-#          bash -c '
-#              path="${PWD//\//\\/}";
-#              grey="\x1b\[90m"
-#              end="\x1b\[0m"
-#              code_group="(${grey}).*?\(report(\w+)\)";
-#              git_root=$(git rev-parse --show-toplevel);
-#              regex="\x20+(?:${git_root})/([^\r\n]*?)(?:[\r\n].*?)?${code_group}";
-#              output="\$1 \$2(\$3)";
-#              result=$(script -fqc "pyright $*" /dev/null | rg --multiline --multiline-dotall "$regex" -or "$output");
-#              count=$(echo -n "$result" | grep -c "^");
-#              if [ "$count" -ne 0 ]; then
-#                  echo "$result";
-#                  echo -e "\033[1;31mFound ${count} error(s)\033[0m";
-#                  exit 1;
-#              fi
-#          ' --
-        files: '^src/|^tests/'
   # mypy
   - repo: local
     hooks:
@@ -173,3 +142,40 @@ repos:
           - "--hide-error-end"
           - "--no-pretty"
           - "--"
+  # pyright-wrapper
+  - repo: https://github.com/randolf-scholz/assorted-hooks.git
+    rev: v0.6.15
+    hooks:
+        - id: pyright-concise
+          files: '^src/|^tests/'
+  # pyright
+  - repo: https://github.com/RobertCraigie/pyright-python
+    rev: v1.1.397
+    hooks:
+      - id: pyright
+        # SEE: https://stackoverflow.com/a/20401674
+        #        entry: sh -c '! script -c "pyright $*" /dev/null | grep --color=never -Po "(?<=$PWD/)(.*:.*)"' --
+        # simple grep: grep --color=never -Po "$PWD/.*:.*"
+        # better ripgrep: rg --multiline --multiline-dotall "($PWD/[^\n]*?)(?:\n.*?)?(\(report\w+\))" -or '$1 $2'
+        # perl:  perl -0777 -ne "while (/((?:\x20+)(${path}[^\n\r]*?)(?:[\r\n].*?)?(\(report\w+\)))/gms) { print \"\$1 \$2\n\"}"
+        # FIXME: some weird issues with ripgrep + script.
+        # NOTE: The issue is likely control characters that are not being handled correctly.
+        #   In fact, it turns out the problem is precisely carriage return. We need to check [\n\r] instead of just \n
+        #        entry: |
+        #          bash -c '
+        #              path="${PWD//\//\\/}";
+        #              grey="\x1b\[90m"
+        #              end="\x1b\[0m"
+        #              code_group="(${grey}).*?\(report(\w+)\)";
+        #              git_root=$(git rev-parse --show-toplevel);
+        #              regex="\x20+(?:${git_root})/([^\r\n]*?)(?:[\r\n].*?)?${code_group}";
+        #              output="\$1 \$2(\$3)";
+        #              result=$(script -fqc "pyright $*" /dev/null | rg --multiline --multiline-dotall "$regex" -or "$output");
+        #              count=$(echo -n "$result" | grep -c "^");
+        #              if [ "$count" -ne 0 ]; then
+        #                  echo "$result";
+        #                  echo -e "\033[1;31mFound ${count} error(s)\033[0m";
+        #                  exit 1;
+        #              fi
+        #          ' --
+        files: '^src/|^tests/'
